---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: jenkins
  labels:
    chart: jenkins
spec:
  chartGitPath: jenkins
  releaseName: devtoolsv1
  values:
    image: jenkins/jenkins
    tag: 2.124-slim
